### ISSUE TITLE
I know this may sound anonying...

### ISSUE THREAD

**Issue by ghost** [ariankordi/closedverse#1]
I know you say look up how to set up a django app, I am a very very beginner at python and all this. I looked up and researched on how to do it but I dont understand still, I have installed all requirements but its still getting all kinds of errors like "NoModuleFoundError: No module named 'closedverse.settings'". I know you might not be able to help :( but I really could use some help rn

**Comment by MegaLoler** [comment]
hi!  i'm not quite able to get it running myself, but the best i can manage is this:

for the closedverse.settings, copy/rename the file `closedverse/settings_default.py` to `closedverse/settings.py`, and then open it up and change `SECRET_KEY = ''` to `SECRET_KEY = 'something'` and also go down to `DATABASES = {` and fill in your mysql information (if you haven't already, make sure you have mysql running, and that you have created a new database for closedverse to use, and put the name of that database in the `NAME` field)

then do `python manage.py migrate` to initialize the database, and then finally `python manage.py runserver` to run it
and once it's running, open your webbrowser and visit http://localhost:8000/

except... i'm get `Foreign key constraint is incorrectly formed` when trying to migrate `admin` and i'm not sure how to solve that ^^;;

**Comment by ariankordi** [comment]
for the purpose of closing this issue: it is planned to make it clearer how to set this up, like other Arian Kordi creations. but that's as if any of this even matters i mean i m talking to a GHOST right now
