### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by AL3XPI** [ariankordi/closedverse#11]
The title explains it all. I'm using Firefox Quantum 64.0 (latest version) on Windows 10. My internet connection is perfectly fine, yet I can't sign up on this darn website.
![](https://screenshotscdn.firefoxusercontent.com/images/80285027-b39f-4661-a687-059e3b0380a4.png)

**Comment by OhHeyItsPip** [comment]
Sign ups are shut down currently, and with the potential sunset of the site soon, this might be forever

**Comment by ariankordi** [comment]
> Sign ups are shut down currently, and with the potential sunset of the site soon, this might be forever

aged so well
