### ISSUE TITLE
Cannot sign up (new error msg)

### ISSUE THREAD

**Issue by AL3XPI** [ariankordi/closedverse#14]
When I choose to sign up, I get this error
![closedverseerror](https://user-images.githubusercontent.com/35903333/53273207-5d18b880-36c1-11e9-8718-dc6a11701462.PNG)
I am on Firefox Quantum Ver. 65 (latest) I know I asked about this before, but now it is actually giving me an error that has something to do with the code.

**Comment by ariankordi** [comment]
for the purpose of closing this issue: these error messages sucked anyway bc the backtrace is truncated and is overall confusing, so it has been added to my todo list to make these errors better
rip closed worse
