### ISSUE TITLE
Artwork canvas draws even when no buttons are being pressed (Firefox Quantum)

### ISSUE THREAD

**Issue by eblu3** [ariankordi/closedverse#3]
this isn't how it works at all
![in action](https://drive.google.com/uc?id=1c-BesJlp1itv11P5xDjWAntVzDU9yjPb)

**Comment by ariankordi** [comment]
I don't know how or why this happens with Gecko browsers, can you fix it yourself?

**Comment by ariankordi** [comment]
for the purpose of closing this issue: i just fixed this in indigo so a similar fix would be trivial for closed curse

**Comment by eblu3** [comment]
Wow! I forgot about this one and didn't know that Miiverse clones were
still being worked on. Thanks for coming around to the issue that my
16-year-old self didn't care to properly explain. ✌️

**Comment by ariankordi** [comment]
It's even more surprising that you responded, but we can thank GitHub's emails for that, I suppose.
Some people are still working on clones, yes, though I don't necessarily plan to support this one a whole lot. I just thought it might be funny to mysteriously fix issues in Grape/Closedverse/Indigo and wait for someone to notice. I have had a list and some local commits lined up to do this.
You can see that I just merged a bunch of stuff for Indigo: https://github.com/PF2M/Indigo/commits/dev and you will also see the Firefox drawboard fix here.
